# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts_223_FZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(default=0)),
                ('org_url', models.CharField(max_length=1000)),
                ('email_1', models.CharField(blank=True, max_length=1000)),
                ('email_2', models.CharField(blank=True, max_length=1000)),
                ('fio', models.CharField(blank=True, max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=1000)),
                ('fax', models.CharField(blank=True, max_length=1000)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('company_url', models.CharField(blank=True, max_length=1000)),
                ('date_modified', models.DateTimeField(verbose_name=b'date modified')),
            ],
            options={
                'verbose_name': 'Contacts_223_FZ',
            },
        ),
        migrations.CreateModel(
            name='Contacts_44_FZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(default=0)),
                ('org_url', models.CharField(max_length=1000)),
                ('email_1', models.CharField(blank=True, max_length=1000)),
                ('email_2', models.CharField(blank=True, max_length=1000)),
                ('fio', models.CharField(blank=True, max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=1000)),
                ('fax', models.CharField(blank=True, max_length=1000)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('company_url', models.CharField(blank=True, max_length=1000)),
                ('date_modified', models.DateTimeField(verbose_name=b'date modified')),
            ],
            options={
                'verbose_name': 'Contacts_44_FZ',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=1000)),
                ('org_region', models.CharField(max_length=1000)),
                ('org_level', models.CharField(max_length=1000)),
                ('org_powers', models.CharField(max_length=1000)),
                ('works_with_44', models.BooleanField(default=False)),
                ('works_with_223', models.BooleanField(default=False)),
                ('date_modified', models.DateTimeField(verbose_name=b'date modified')),
                ('date_checked', models.DateTimeField(verbose_name=b'date checked')),
            ],
            options={
                'verbose_name': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=1000)),
                ('region_code', models.CharField(max_length=1000)),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name=b'date completed')),
                ('date_checked', models.DateTimeField(blank=True, null=True, verbose_name=b'date checked')),
            ],
            options={
                'verbose_name': 'Region',
            },
        ),
    ]
