# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts_223_fz',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_manager.Organizations'),
        ),
        migrations.AlterField(
            model_name='contacts_44_fz',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_manager.Organizations'),
        ),
    ]
