# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_manager', '0002_auto_20160201_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts_223_fz',
            name='additional_contact',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='contacts_44_fz',
            name='additional_contact',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
