# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_manager', '0004_auto_20160202_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='org_powers_223',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='org_powers_44',
        ),
    ]
